install:
  - SET "PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%"
  - C:\msys64\usr\bin\pacman --noconfirm -Syyuu
  - C:\msys64\usr\bin\pacman -S --noconfirm mingw-w64-x86_64-{toolchain,gcc,clang,cmake,ninja,libxml2,pugixml,libjpeg-turbo,zlib}

environment:
  CFLAGS: "-pipe"
  CXXFLAGS: "-pipe"
  ECO: "-DALLOW_DOWNLOADING_GOOGLETEST=ON"
  TARGET: build
  matrix:
    - CC:  cc
      CXX: c++
    - CC:  clang
      CXX: clang++
    - CC:  cc
      CXX: c++
      FLAVOR: Coverage

# clang Coverage build fails with some llvm linking issues

matrix:
  fast_finish: true

build_script:
  - SET "PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%"
  - C:\msys64\usr\bin\bash --login -c "
      export PATH=/c/msys64/mingw64/bin:/c/msys64/usr/bin:$PATH;
      export SRC_DIR=\"${APPVEYOR_BUILD_FOLDER}\";
      export BUILD_DIR=\"$SRC_DIR/build\";
      export INSTALL_PREFIX=\"$SRC_DIR/install\";
      mkdir \"${BUILD_DIR}\";
      mkdir \"${INSTALL_PREFIX}\";
      $(cygpath ${APPVEYOR_BUILD_FOLDER})/.ci/ci-script.sh;"

on_success:
  - SET "PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%"
  - C:\msys64\usr\bin\bash --login -c "
      if [[ "$FLAVOR" != "Coverage" ]]; then
        exit;
      fi;
      export PATH=/c/msys64/mingw64/bin:/c/msys64/usr/bin:$PATH;
      export PLATFORM=windows;
      export CXX=GCC;
      cd \"${APPVEYOR_BUILD_FOLDER}\";
      curl -s https://codecov.io/bash > codecov;
      chmod +x codecov;
      ./codecov -e PLATFORM,CXX -F unittests -X gcov -s \"${APPVEYOR_BUILD_FOLDER}/build/gcov-reports-unittest\" -Z;
